// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zippy.Data.Context;

#nullable disable

namespace Zippy.Migrations
{
    [DbContext(typeof(ZippyDbContext))]
    [Migration("20250912013929_InitializingDatabase")]
    partial class InitializingDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Zippy.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("resources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dfced651-e327-4052-8bc6-7c739c86f431"),
                            CreatedAt = new DateTime(2025, 9, 12, 1, 39, 28, 456, DateTimeKind.Utc).AddTicks(7538),
                            Key = "resource1-key",
                            Name = "Resource 1",
                            Url = "https://github.com/wisdomtochi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
