// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zippy.Data.Context;

#nullable disable

namespace Zippy.Migrations
{
    [DbContext(typeof(ZippyDbContext))]
    partial class ZippyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Zippy.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Alias")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("resources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0c3a065-4f8b-4fcd-b924-6b317417e18c"),
                            Alias = "Resource 1",
                            CreatedAt = new DateTime(2025, 9, 13, 18, 42, 15, 947, DateTimeKind.Utc).AddTicks(3200),
                            Key = "resource1-key",
                            Url = "https://github.com/wisdomtochi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
